version: '3.8'

services:
  node:
    build: .
    container_name: ical-feed-node
    ports:
      - "${NODE_PORT_EXTERN}:${NODE_PORT_INTERN}"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

volumes:
  mongo_data:
